namespace :api do
  get '/bike_model/model_auto_complete', to: 'bike_model#model_auto_complete'
  get '/customers/suggest', to: 'customers#suggest'
  get '/customers/suggest_byfield', to: 'customers#suggest_byfield'
  get '/customers/find', to: 'customers#find'
  get '/customers/:id/owned_bikes', to: 'customers#owned_bikes'
  get '/customers/:id/histories', to: 'customers#histories'
  get '/customers/search_checkin', to: 'customers#search_checkin'
  get '/customers/checkin', to: 'customers#checkin'
  get '/customers/checkin/:checkin_day', to: 'customers#checkin'
  post '/customers/valid_phone_number', to: 'customers#valid_phone_number'
  post '/customers/valid_numberplate', to: 'customers#valid_numberplate'
  get '/shop_products/suggest', to: 'shop_products#suggest'
  get '/shop_products/quicksearch', to: 'shop_products#quicksearch'
  get '/shop_products/history', to: 'shop_products#history'
  get '/shop_products/list', to: 'shop_products#list'
  get '/shop_products/list/:id', to: 'shop_products#list_detail'
  post '/shop_products/create', to: 'shop_products#create'
  post '/receipt/resend_sms/:checkin_id', to: 'receipt#resend_sms'
  get '/customers/:id/is_optin', to: 'customers#is_optin'
  get '/customize_shop_product_lists', to: 'customize_shop_product_lists#index'
  get '/customize_shop_product_lists/:id', to: 'customize_shop_product_lists#find'
  put '/customize_shop_product_lists/update_list', to: 'customize_shop_product_lists#update_list'
  post '/customize_shop_product_lists', to: 'customize_shop_product_lists#create'
  put '/customize_shop_product_lists/:id', to: 'customize_shop_product_lists#update'
  delete '/customize_shop_product_lists/:id', to: 'customize_shop_product_lists#destroy'

  namespace :admin do
    get '/shop_products/list', to: 'shop_products#list', as: 'shop_products_list'
    get '/shop_products/product_categories', to: 'shop_products#product_categories', as: 'shop_products_product_categories'
    get '/shop_products/product_sort', to: 'shop_products#product_sort', as: 'shop_products_product_sort'
    get '/shop_products/admin_products', to: 'shop_products#admin_products', as: 'shop_products_admin_products'
    get '/shop_products/check_progress_delete', to: 'shop_products#check_progress_deleted', format: 'json'
    put '/shop_products/update', to: 'shop_products#update', as: 'shop_products_update'
    post '/shop_products/create', to: 'shop_products#create', as: 'shop_products_create'
    put '/shop_products/update_product', to: 'shop_products#update_product', as: 'shop_products_update_product'
    get '/shop_products/stock_controls', to: 'shop_products#stock_controls', as: 'shop_products_stock_controls'
    get '/shop_products/variants', to: 'shop_products#variants', as: 'shop_products_variants'
    get '/shop_products/tech_specs', to: 'shop_products#tech_specs', as: 'shop_products_tech_specs'
    delete '/shop_products/delete', to: 'shop_products#soft_delete'


    get '/admin_products/list', to: 'admin_products#list', as: 'admin_products_list'
    get '/admin_products/product_categories', to: 'admin_products#product_categories', as: 'admin_products_product_categories'
    get '/admin_products/brands', to: 'admin_products#brands', as: 'admin_products_brands'
    get '/admin_products/variants', to: 'admin_products#variants', as: 'admin_products_variants'
    get '/admin_products/tech_specs', to: 'admin_products#tech_specs', as: 'admin_products_tech_specs'
    put '/admin_products/import', to: 'admin_products#import', as: 'admin_products_import'

    get '/shop_invoices/list', to: 'shop_invoices#list', as: 'shop_invoices_list'
    get '/shop_invoices/:id', to: 'shop_invoices#find', as: 'shop_invoices_find'
    post '/shop_invoices/update', to: 'shop_invoices#update', as: 'shop_invoices_update'
    post '/shop_invoices/create', to: 'shop_invoices#create', as: 'shop_invoices_create'
    delete '/shop_invoices/:id', to: 'shop_invoices#destroy'

    get '/suppliers/:shop_id', to: 'suppliers#list', as: 'suppliers_list', format: 'json'

    get '/product_non_active/list', to: 'product_non_active#list', as: 'product_non_active'
    put '/product_non_active/restore_deleted', to: 'product_non_active#restore_deleted_product', as: 'product_non_active_restore'
  end
end
